# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code_editor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import project_manager as PM


class Ui_CodeEditorWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saved_code_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.saved_code_group_box.setGeometry(QtCore.QRect(10, 10, 271, 401))
        self.saved_code_group_box.setObjectName("saved_code_group_box")
        self.list_widget = QtWidgets.QListWidget(self.saved_code_group_box)
        self.list_widget.setGeometry(QtCore.QRect(10, 20, 251, 371))
        self.list_widget.setObjectName("list_widget")
        self.code_editor_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.code_editor_group_box.setGeometry(QtCore.QRect(310, 10, 481, 511))
        self.code_editor_group_box.setObjectName("code_editor_group_box")
        self.text_edit_widget = QtWidgets.QPlainTextEdit(self.code_editor_group_box)
        self.text_edit_widget.setGeometry(QtCore.QRect(10, 20, 461, 481))
        self.text_edit_widget.setObjectName("text_edit_widget")
        self.text_edit_widget.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.new_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_file_button.setGeometry(QtCore.QRect(10, 420, 81, 23))
        self.new_file_button.setObjectName("new_file_button")
        self.load_selected_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_selected_button.setGeometry(QtCore.QRect(104, 420, 81, 23))
        self.load_selected_button.setObjectName("load_selected_button")
        self.save_update_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_update_button.setGeometry(QtCore.QRect(500, 530, 111, 21))
        self.save_update_button.setObjectName("save_update_button")
        self.import_code_button = QtWidgets.QPushButton(self.centralwidget)
        self.import_code_button.setGeometry(QtCore.QRect(104, 460, 81, 23))
        self.import_code_button.setObjectName("import_code_button")
        self.export_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_all_button.setGeometry(QtCore.QRect(104, 530, 81, 23))
        self.export_all_button.setObjectName("export_all_button")
        self.delete_selected_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_selected_button.setGeometry(QtCore.QRect(200, 420, 81, 23))
        self.delete_selected_button.setObjectName("delete_selected_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.close_editor_menu_action = QtWidgets.QAction(MainWindow)
        self.close_editor_menu_action.setObjectName("close_editor_menu_action")
        self.menuMenu.addAction(self.close_editor_menu_action)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)

        self.close_editor_menu_action.triggered.connect(lambda: exit())
        self.list_widget.itemClicked.connect(MainWindow.itemSelected)
        self.save_update_button.clicked.connect(MainWindow.saveUpdate)
        self.load_selected_button.clicked.connect(MainWindow.loadFile)
        self.new_file_button.clicked.connect(MainWindow.createFile)
        self.delete_selected_button.clicked.connect(MainWindow.deleteFile)
        self.import_code_button.clicked.connect(MainWindow.importFile)
        self.export_all_button.clicked.connect(MainWindow.exportFiles)

        if not PM.CURRENT_LOADED_FILE:
            self.text_edit_widget.clear()
            self.text_edit_widget.setReadOnly(True)
            self.text_edit_widget.setStyleSheet("background-color: rgb(211, 211, 211);")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saved_code_group_box.setTitle(_translate("MainWindow", "Saved Code Files"))
        self.code_editor_group_box.setTitle(_translate("MainWindow", "Code Editor"))
        self.new_file_button.setText(_translate("MainWindow", "New File"))
        self.load_selected_button.setText(_translate("MainWindow", "Load Selected"))
        self.save_update_button.setText(_translate("MainWindow", "Save/Update Code"))
        self.import_code_button.setText(_translate("MainWindow", "Import Code"))
        self.export_all_button.setText(_translate("MainWindow", "Export All"))
        self.delete_selected_button.setText(_translate("MainWindow", "Delete Selected"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.close_editor_menu_action.setText(_translate("MainWindow", "Close Editor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CodeEditorWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
