# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_account_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial


class Ui_CreateAccount(object):
    def setupUi(self, CreateAccount):
        CreateAccount.setObjectName("CreateAccount")
        CreateAccount.resize(800, 600)
        CreateAccount.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CreateAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 145, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 215, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 285, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 150, 231, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 220, 231, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 290, 231, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 460, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        CreateAccount.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateAccount)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        CreateAccount.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateAccount)
        self.statusbar.setObjectName("statusbar")
        CreateAccount.setStatusBar(self.statusbar)

        self.retranslateUi(CreateAccount)
        self.pushButton.clicked.connect(partial(CreateAccount.processCreation, self.lineEdit, self.lineEdit_2, self.lineEdit_3))
        self.pushButton_2.clicked.connect(CreateAccount.loginWindow)

        QtCore.QMetaObject.connectSlotsByName(CreateAccount)

    def retranslateUi(self, CreateAccount):
        _translate = QtCore.QCoreApplication.translate
        CreateAccount.setWindowTitle(_translate("CreateAccount", "Create Account"))
        self.label.setText(_translate("CreateAccount", "Account Creation"))
        self.label_2.setText(_translate("CreateAccount", "Username: "))
        self.label_3.setText(_translate("CreateAccount", "Password: "))
        self.label_4.setText(_translate("CreateAccount", "Email: "))
        self.pushButton.setText(_translate("CreateAccount", "Create"))
        self.pushButton_2.setText(_translate("CreateAccount", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateAccount = QtWidgets.QMainWindow()
    ui = Ui_CreateAccount()
    ui.setupUi(CreateAccount)
    CreateAccount.show()
    sys.exit(app.exec_())
