# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.project_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.project_list_widget.setGeometry(QtCore.QRect(150, 110, 331, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.project_list_widget.setFont(font)
        self.project_list_widget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.project_list_widget.setWordWrap(True)
        self.project_list_widget.setSelectionRectVisible(True)
        self.project_list_widget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.project_list_widget.setObjectName("project_list_widget")
        self.create_new_project_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_new_project_button.setGeometry(QtCore.QRect(160, 380, 131, 23))
        self.create_new_project_button.setObjectName("create_new_project_button")
        self.open_selected_project_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_selected_project_button.setEnabled(True)
        self.open_selected_project_button.setGeometry(QtCore.QRect(350, 380, 121, 23))
        self.open_selected_project_button.setObjectName("open_selected_project_button")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(540, 10, 75, 23))
        self.logout_button.setObjectName("logout_button")
        self.open_editor_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_editor_button.setGeometry(QtCore.QRect(270, 440, 101, 23))
        self.open_editor_button.setObjectName("open_editor_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)

        self.project_list_widget.itemClicked.connect(MainWindow.itemSelected)
        self.create_new_project_button.clicked.connect(MainWindow.createProject)
        self.open_selected_project_button.clicked.connect(MainWindow.openSelectedProject)
        self.logout_button.clicked.connect(MainWindow.logout)
        self.actionExit.triggered.connect(lambda: exit())
        self.open_editor_button.clicked.connect(MainWindow.openCodeEditor)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Projects"))
        self.create_new_project_button.setText(_translate("MainWindow", "Create New Project"))
        self.open_selected_project_button.setText(_translate("MainWindow", "Open Selected Project"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.open_editor_button.setText(_translate("MainWindow", "Open Code Editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
